export const STAGES = [
  'Not contacted','Email sent','Follow-up in progress',
  'Replied','Call booked','Proposal sent','Lost / Not a fit'
];

export const EXTRA_STAGES = {
  spoken: 'Spoken To',
  meeting: 'Meeting Booked',
};

export const prospects = [
  { id:1, name:'Neil Bansal', initials:'NB', title:'MD, Operations & Strategy', company:'OMERS Private Equity', sector:'PE/VC', location:'New York, NY', stage:1, bant:{b:5,a:5,n:5,t:4}, priority:true, email:'Enrichment required', linkedin:'linkedin.com/in/neil-bansal-omers', signal:'North Highland acquired The Bridge (data & AI firm) on his watch — AI mandate actively deploying across portfolio. $145B AUM fund, dedicated Ops & Strategy team.', lastContact:'2026-05-30', notes:'Cold email sent referencing North Highland / The Bridge AI acquisition. Awaiting reply.', researchDone:true, outreachWritten:true, source:'Manual' },
  { id:2, name:'James Dale', initials:'JD', title:'Chief Technology Officer', company:'ApolloMD', sector:'Healthcare', location:'Atlanta, GA', stage:2, bant:{b:4,a:5,n:5,t:5}, priority:true, email:'Enrichment required', linkedin:'linkedin.com/in/james-dale-apollomd', signal:'ApolloMD deployed agentic AI via Adonis (Apr 2025) — 90% autonomous resolution rate across 1,800 clinicians. Data breach investigation Sep 2025 = urgent security + infrastructure mandate. CTO since 2012.', lastContact:'2026-05-30', notes:'5-touch sequence written. Research complete. 100+ hospital partners nationally. Competitor to Sound Physicians — use that case study.', researchDone:true, outreachWritten:true, source:'Manual' },
  { id:3, name:'Deepak Batra', initials:'DB', title:'PE Operating Exec | Triage-CIO', company:'Lee Equity Partners', sector:'PE/VC', location:'New York, NY', stage:0, bant:{b:5,a:5,n:5,t:4}, priority:true, email:'Enrichment required', linkedin:'linkedin.com/in/deepak-batra', signal:'Title literally says "Triage-CIO" — already understands and buys fractional CIO services. Lee Equity backs healthcare & business services portfolio companies.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:4, name:'Dan Pr***d', initials:'DP', title:'Chief Technology Officer', company:'Specialized Dental Partners', sector:'Dental', location:'United States', stage:0, bant:{b:4,a:5,n:5,t:4}, priority:true, email:'Enrichment required', linkedin:'Enrichment required', signal:'PE-backed dental DSO — exact same sector as Clove Dental. Multi-state expansion creates immediate digital infrastructure and patient ops need.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:5, name:'Scott Ha***n', initials:'SH', title:'Managing Partner & COO', company:'Gridiron Capital', sector:'PE/VC', location:'New Canaan, CT', stage:0, bant:{b:5,a:5,n:4,t:3}, priority:true, email:'Enrichment required', linkedin:'Enrichment required', signal:'Dual MP+COO role = no dedicated tech layer. Mid-market PE, 3–10 active platforms. Classic fractional CIO entry point.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:6, name:'Merced Go***s', initials:'MG', title:'CIO / CTO', company:'HNI Healthcare', sector:'Healthcare', location:'Houston, TX', stage:0, bant:{b:4,a:5,n:5,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'PE-backed hospitalist group. Dual CIO/CTO role signals under-resourced IT leadership — same profile as Sound Physicians.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:7, name:'David Ha***n', initials:'DH', title:'Chief Information Officer', company:'Apex Dental Partners', sector:'Dental', location:'United States', stage:0, bant:{b:4,a:5,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Growing dental DSO, PE-backed, scaling fast. CIO in seat = IT gap formally acknowledged. High probability of fractional support or IT due diligence engagement.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:8, name:'Ben Ro***e', initials:'BR', title:'Chief Information Officer', company:'Rodeo Dental & Orthodontics', sector:'Dental', location:'Dallas, TX', stage:0, bant:{b:4,a:5,n:4,t:4}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Fast-growing multi-state DSO in Dallas. Consumer-focused brand — perfect fit for digital front-door work proven at Clove Dental.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:9, name:'Steven Mo***l', initials:'SM', title:'Executive Managing Partner', company:'Argosy Private Equity', sector:'PE/VC', location:'Wayne, PA', stage:0, bant:{b:4,a:5,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Argosy targets $5M–$30M EBITDA — classic fragmented-tech lower mid-market. Underserved by big consulting firms, clean entry point.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:10, name:'Brian Ho***t', initials:'BH', title:'Chief Operating Officer', company:'Parkway Venture Capital', sector:'PE/VC', location:'United States', stage:0, bant:{b:3,a:4,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'VC COO manages portfolio ops infrastructure. Parkway targets healthcare and tech startups — direct overlap with client base.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:11, name:'John Gu***a', initials:'JG', title:'CTO / CIO', company:'Liberty Healthcare', sector:'Healthcare', location:'United States', stage:0, bant:{b:4,a:5,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Multi-site healthcare corp, dual CTO/CIO = bandwidth-constrained executive. Complex data and compliance needs — prime AI/LLM infrastructure opportunity.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:12, name:'Terry Ba***t', initials:'TB', title:'Chief Information Officer', company:'Benco Dental', sector:'Dental', location:'Pittston, PA', stage:0, bant:{b:4,a:5,n:3,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Largest privately held dental distributor — complex operational tech stack supporting thousands of dental practices nationwide.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:13, name:'Yatish Mi***a', initials:'YM', title:'Operating Partner', company:'Impact Venture Capital', sector:'PE/VC', location:'United States', stage:0, bant:{b:3,a:4,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Impact-focused VC — portfolio companies often have lean tech teams with no dedicated CIO layer. High probability of fractional engagement across 2–3 portfolio companies.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:14, name:'Lauren De***a', initials:'LD', title:'Managing Partner', company:'Motivate Venture Capital', sector:'PE/VC', location:'United States', stage:0, bant:{b:3,a:5,n:3,t:3}, priority:false, email:'Has email — enrichment required', linkedin:'Enrichment required', signal:'MP-level with confirmed email in Apollo. Healthcare-adjacent VC. Decision authority to engage advisory services without committee approval.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:15, name:'Gavin Ba***r', initials:'GB', title:'CIO & Managing Partner', company:'Atreides Management', sector:'PE/VC', location:'New York, NY', stage:0, bant:{b:4,a:5,n:3,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'CIO+MP combo at growth-focused fund. Technology and consumer portfolio — dual entry point for advisory services at both fund and portfolio level.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:16, name:'Havell Ro***s', initials:'HR', title:'CEO & Managing Partner', company:'New Majority Capital', sector:'PE/VC', location:'United States', stage:0, bant:{b:3,a:5,n:3,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'PE targeting underserved mid-market companies at early digital transformation stage. CEO+MP = fastest deal cycle, single decision maker.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:17, name:'Saurabh Su***i', initials:'SS', title:'Founding Managing Partner', company:'CerraCap Impact VC', sector:'PE/VC', location:'United States', stage:0, bant:{b:3,a:5,n:3,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Healthcare-tech VC portfolio. Founding MP = single decision maker. Portfolio companies often lack enterprise-grade IT infrastructure — strong AI readiness assessment opportunity.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:18, name:'Dylan Rh***s', initials:'DR', title:'CTO, Operating Partner', company:'Andreessen Horowitz', sector:'PE/VC', location:'San Francisco, CA', stage:0, bant:{b:5,a:4,n:3,t:3}, priority:false, email:'Has email — enrichment required', linkedin:'Enrichment required', signal:'a16z Operating Partners support portfolio companies directly. Dylan fields inbound requests from portfolio CTOs. Relationship unlocks multi-portfolio access — not just one deal.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:19, name:'James McGlynn', initials:'JM', title:'Managing Director', company:'OMERS Private Equity', sector:'PE/VC', location:'Toronto', stage:0, bant:{b:5,a:4,n:4,t:4}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Secondary OMERS PE contact — same firm as Neil Bansal (primary). Use as parallel outreach path if Neil is unresponsive after touch 3.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:20, name:'Sean Li***n', initials:'SL', title:'Partner | Operating CIO/CTO', company:'Fortium Partners', sector:'Advisory', location:'United States', stage:0, bant:{b:2,a:3,n:2,t:2}, priority:false, email:'Has email — enrichment required', linkedin:'Enrichment required', signal:'Fractional CIO firm — COMPETITOR / potential channel partner. Do not treat as direct sales prospect. Use partnership outreach track instead.', lastContact:null, notes:'FLAG: Competitor / potential channel partner. Do not send standard sales sequence.', researchDone:false, outreachWritten:false, source:'Manual' },
  { id:21, name:'Rick V***', initials:'RV', title:'Vice President, Information Technology', company:'MB2 Dental', sector:'Dental', location:'Dallas, TX', stage:0, bant:{b:4,a:4,n:5,t:4}, priority:true, email:'Enrichment required', linkedin:'Enrichment required', signal:'MB2 Dental is KKR-backed — one of the largest dental DSOs in the US with 700+ locations across 43 states. Active multi-state expansion = immediate digital infrastructure and patient ops need. Identical profile to Clove Dental win.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:22, name:'Maria Me***a', initials:'MM', title:'Operating Partner', company:'AUA Private Equity Partners', sector:'PE/VC', location:'New York, NY', stage:0, bant:{b:4,a:5,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'AUA PE focuses on healthcare services and specialty practices — Operating Partner title means she owns value creation across portfolio. Direct overlap with Sound Physicians and Oshi Health reference clients.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:23, name:'Michelle Ha***n', initials:'MH', title:'Special Venture Partner', company:'Galen Partners', sector:'Healthcare', location:'New York, NY', stage:0, bant:{b:4,a:4,n:5,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Galen Partners is a healthcare-focused PE/VC firm with 30+ years and $1B+ deployed. Venture Partner = portfolio company support and value creation. Healthcare portfolio companies routinely need fractional CIO and IT assessment work.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:24, name:'Tucker Mo***n', initials:'TM', title:'Vice President, Portfolio Operations', company:'Accel-KKR', sector:'PE/VC', location:'Menlo Park, CA', stage:0, bant:{b:4,a:4,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'VP Portfolio Operations at a $15B tech-focused PE fund. Owns operational improvement across portfolio companies — directly fields requests from portfolio CTOs and CIOs. Relationship unlocks multi-portfolio access.', lastContact:null, notes:'Accel-KKR has a large internal team — qualify carefully. Use partnership/advisor angle.', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:25, name:'John An***o', initials:'JA', title:'Operating Partner', company:'TriArtisan Capital Advisors', sector:'PE/VC', location:'New York, NY', stage:0, bant:{b:4,a:5,n:3,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'TriArtisan is a NYC-based mid-market PE firm focused on consumer, restaurant and business services. Operating Partner owns tech and operational value creation across 5–8 active platforms — classic fractional CIO entry point.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:26, name:'Ames Ly***n', initials:'AL', title:'Vice President, Portfolio Operations', company:'Denali Growth Partners', sector:'PE/VC', location:'Dallas, TX', stage:0, bant:{b:4,a:4,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Dallas-based growth equity firm investing in lower mid-market B2B services and healthcare companies. VP Portfolio Ops = tech gap management across all active platforms. Healthcare overlap is strong.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:27, name:'Reinhold Do***l', initials:'RD', title:'Chief Information Officer', company:'South Shore Hospital', sector:'Healthcare', location:'South Weymouth, MA', stage:0, bant:{b:3,a:5,n:4,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'South Shore Health is an independent community health system. CIO in seat with lean team. Multi-site hospital network with EHR complexity = AI infrastructure and IT assessment opportunity.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' },
  { id:28, name:'Don Ba***m', initials:'DB2', title:'VP, IT & Security | CISO / CTO', company:'Rubicon Founders', sector:'PE/VC', location:'Nashville, TN', stage:0, bant:{b:3,a:4,n:3,t:3}, priority:false, email:'Enrichment required', linkedin:'Enrichment required', signal:'Nashville-based PE/VC firm. Triple title (VP IT + CISO + CTO) = one person covering three domains — classic under-resourced IT leadership signal. Strong fractional advisory opportunity.', lastContact:null, notes:'', researchDone:false, outreachWritten:false, source:'Apollo Agent' }
];

export const icpProfile = {
  titles: ['Managing Partner','Operating Partner','VP Portfolio Operations','Head of Value Creation','CIO','CTO','CEO','COO'],
  sectors: ['Private Equity','Venture Capital','Healthcare','Dental','Retail','SaaS'],
  geography: ['New York','Chicago','San Francisco','Boston','Los Angeles','Houston','Dallas'],
  companySize: '$250M–$5B AUM (PE/VC fund) · $20M–$500M revenue (portfolio company)',
  seniority: ['C-Suite','VP','Partner','Director']
};

export const buyingTriggers = [
  { num:'01', title:'New PE acquisition or funding round closed', desc:'0–12 months ago — triggers 100-day value creation plan. IT assessment and leadership gaps are top of the agenda. Highest-conversion window.' },
  { num:'02', title:'Active hiring for CIO, CTO, VP of IT, or AI roles', desc:'Job posts signal a known gap. Fractional engagement is faster, cheaper, and de-risked vs a 6-month executive search. Budget already exists.' },
  { num:'03', title:'M&A tuck-in at portfolio company level', desc:'Portfolio company acquires a tuck-in or merges business units. Immediate tech fragmentation — ERP mismatches, duplicate data systems, competing stacks.' },
  { num:'04', title:'CXO departure — CIO, CTO, or CDO recently left', desc:'Tech leader leaving = immediate power vacuum and institutional knowledge loss. Fractional CIO is the fastest bridge solution available.' },
  { num:'05', title:'Board / LP pressure on AI strategy', desc:'Public statements or job posts mentioning "AI strategy" or "digital transformation" indicate board-level mandate. Budget real, roadmap missing.' }
];

export const bestClients = [
  { name:'Sound Physicians', desc:'$1B+ multi-specialty group, 4,000+ providers', work:'End-to-end IT assessment + modern analytics and AI/LLM infrastructure deployment', sector:'Healthcare' },
  { name:'Oshi Health', desc:'Fast-growing healthcare company', work:'100-hour IT audit, product/IT org redesign, record-breaking quarterly performance', sector:'Healthcare' },
  { name:'Clove Dental', desc:'Major dental network', work:'Digital front-door experience + custom application suite for operational efficiency and patient care', sector:'Dental' }
];

export const apolloFilters = {
  titles: ['Managing Partner','Operating Partner','VP Portfolio Operations','Head of Value Creation','CIO','CTO','CEO','COO'],
  seniority: ['C-Suite','VP','Partner','Director'],
  industries: ['Private Equity','Venture Capital','Healthcare','Hospital & Health Care','Consumer & Retail','SaaS / Technology'],
  headcount: ['11–200 (PE/VC fund)','50–2,000 (portfolio co.)'],
  geography: ['New York, NY','Chicago, IL','San Francisco, CA','Boston, MA','Los Angeles, CA','Houston, TX','Dallas, TX'],
  keywords: ['"portfolio company"','"value creation"','"platform company"','"PE-backed"','"growth equity"'],
  technologies: ['Salesforce','HubSpot','Epic','Athenahealth','NetSuite'],
  hiringSignals: ['CIO','VP of Technology','IT Director','Director of Data','AI Engineer']
};

export const disqualifiers = [
  { type:'hard', title:'Large enterprises with mature internal IT', desc:'Companies with 500+ person IT departments, in-house CIO with 5+ years tenure, established tech governance. Fortune 500 and publicly traded firms. They don\'t need fractional leadership.' },
  { type:'hard', title:'Early-stage startups (pre–Series B)', desc:'Companies under $5M revenue or pre-product-market fit. Too early for IT due diligence or Fractional CIO. Budget rarely exists; deal cycles are painful and small.' },
  { type:'hard', title:'PE firms with dedicated internal tech operating partner', desc:'Firms like KKR, Blackstone, or Silver Lake with large internal value-creation teams. They build in-house — you\'re competing with their own employees.' },
  { type:'caution', title:'Fractional CIO competitors (e.g. Fortium Partners)', desc:'These are potential channel/referral partners — not direct prospects. Use a partnership outreach track, not the standard sales sequence.' }
];

export const outreachSequences = {
  neilBansal: {
    prospect: 'Neil Bansal — MD Operations & Strategy, OMERS Private Equity',
    subjectLine: 'OMERS portfolio — AI execution across healthcare holdings',
    touch1: {
      type: 'Cold email',
      subject: 'OMERS portfolio — AI execution across healthcare holdings',
      body: `Neil,\n\nNorth Highland acquiring The Bridge for data and AI capabilities tells me OMERS is serious about building that muscle across the portfolio — not just talking about it.\n\nWe've done this work inside PE-backed healthcare platforms — end-to-end IT assessments, AI infrastructure deployment, and fractional CIO leadership that sticks past the engagement.\n\nSound Physicians ($1B+, 4,000 providers) and Oshi Health are two recent examples.\n\nWhat does the current AI readiness gap look like across your North American healthcare holdings?`
    },
    linkedinRequest: 'Neil — saw that North Highland brought on The Bridge specifically for data and AI. Impressive move. I work with PE-backed healthcare platforms on exactly that execution layer — Fractional CIO, AI assessments, infrastructure. Worth connecting.'
  },
  jamesDale: {
    prospect: 'James Dale — CTO, ApolloMD',
    subjectLine: 'ApolloMD — beyond RCM AI',
    touch1: {
      type: 'Cold email',
      subject: 'ApolloMD — beyond RCM AI',
      body: `James,\n\nThe Adonis partnership is smart — 90% autonomous resolution is a real number. RCM is solved. The harder question is what the AI infrastructure looks like across your 100+ hospital integrations when the use cases go beyond billing.\n\nWe built that layer for Sound Physicians — 4,000 providers, similar operational complexity. End-to-end: assessment, architecture, deployment, embedded talent.\n\nIs clinical AI infrastructure on your roadmap for this year?`
    }
  }
};
